//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UseCases.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UseCases.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postnr.;Bynavn
        ///999;København C
        ///1001;København K
        ///1800;Frederiksberg C
        ///2100;København Ø
        ///2150;Nordhavn
        ///2200;København N
        ///2300;København S
        ///2400;København NV
        ///2412;Grønland
        ///2450;København SV
        ///2500;Valby
        ///2600;Glostrup
        ///2605;Brøndby
        ///2610;Rødovre
        ///2620;Albertslund
        ///2625;Vallensbæk
        ///2630;Taastrup
        ///2635;Ishøj
        ///2640;Hedehusene
        ///2650;Hvidovre
        ///2660;Brøndby Strand
        ///2665;Vallensbæk Strand
        ///2670;Greve
        ///2680;Solrød Strand
        ///2690;Karlslunde
        ///2700;Brønshøj
        ///2720;Vanløse
        ///2730;Herlev
        ///2740;Skovlunde
        ///2750;Ballerup
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Postnummer_v2 {
            get {
                return ResourceManager.GetString("Postnummer_v2", resourceCulture);
            }
        }
    }
}
